default:
    pattern:   /
    defaults:  { _controller: JDACoreBundle:Home:redirect, _locale: ja }
search:
    pattern:   /{_locale}/search
    defaults:  { _controller: JDACoreBundle:Search:index, _locale: ja }
    requirements:
        _locale: en|ja
advsearch:
    pattern:   /{_locale}/advsearch
    defaults:  { _controller: JDACoreBundle:AdvSearch:index, _locale: ja }
    requirements:
        _locale: en|ja
home:
    pattern:   /{_locale}/home
    defaults:  { _controller: JDACoreBundle:Home:index, _locale: ja }
    requirements:
        _locale: en|ja
about:
    pattern:   /{_locale}/about
    defaults:  { _controller: JDACoreBundle:About:index, _locale: ja }
    requirements:
        _locale: en|ja
team:
    pattern:   /{_locale}/team
    defaults:  { _controller: JDACoreBundle:Team:index, _locale: ja }
    requirements:
        _locale: en|ja
contributearchive:
    pattern:   /{_locale}/team
    defaults:  { _controller: JDACoreBundle:Contributearchive:index, _locale: ja }
    requirements:
        _locale: en|ja
collections:
    pattern:   /{_locale}/collections
    defaults:  { _controller: JDACoreBundle:Collections:index, _locale: ja }
    requirements:
        _locale: en|ja
item:
    pattern:   /{_locale}/item/{item_id}
    defaults:  { _controller: JDACoreBundle:Item:index, _locale: ja }
    requirements:
        _locale: en|ja
partners:
    pattern:	/{_locale}/partners
    defaults:	{ _controller: JDACoreBundle:Partners:index, _locale: ja }
    requirements:
        _locale: en|ja   
faq:
    pattern:	/{_locale}/faq
    defaults:	{ _controller: JDACoreBundle:FAQ:index, _locale: ja }
    requirements:
        _locale: en|ja   
user:
    pattern:   /{_locale}/user/{id}
    defaults:  { _controller: JDACoreBundle:User:index}
    requirements:
        _locale: en|ja
        id:  \d+
collection:
    pattern:   /{_locale}/collection/{id}
    defaults:  { _controller: JDACoreBundle:Collection:index}
    requirements:
        _locale: en|ja
        id:  \d+
seedSubmit:
    pattern:   /{_locale}/contribute/
    defaults:  { _controller: JDACoreBundle:SeedSubmit:index, _locale: ja }
    requirements:
        _locale: en|ja
testimonial:
    pattern:   /{_locale}/testimonial/
    defaults:  { _controller: JDACoreBundle:SeedSubmit:testimonial, _locale: ja }
    requirements:
        _locale: en|ja
export:
    pattern:   /export-seeds/
    defaults:  { _controller: JDACoreBundle:Exporter:index }
exported:
    pattern:   /exported/
    defaults:  { _controller: JDACoreBundle:Exporter:getItems }
export_special:
    pattern:   /export_special/
    defaults:  { _controller: JDACoreBundle:Exporter:getItemsSpecial }
batchtag:
    pattern:	/batch-tag/
    defaults:	{ _controller: JDACoreBundle:BatchTag:index }
batchtagged:
    pattern:	/batch-tagged/
    defaults:	{ _controller: JDACoreBundle:BatchTag:update}